title: Phenomenological AI Safety Research Institute
author: PAISRI
email: contact@paisri.org
description: >
  PAIRSI is a nonprofit research organization located in Berkeley, CA, USA.
url: https://paisri.org/
remote_theme: jekyll/minima
permalink: none
#markdown: redcarpet
#pygments: true
timezone: America/Los_Angeles
header_pages:
 - index.md
 - people.md
 - publications.md
